### ISSUE TITLE
UpgradeController Missing

### ISSUE THREAD

**Issue by PhilRumens** [Jumoo/Taskily#1]
When I compile get the error

_Error  1   Source file 'Controllers\UpgradeController.cs' could not be found_

I can get round this by removing it from the project, but I'm not sure how this will affect it.

**Comment by KevinJump** [comment]
Ahh, yes you should be fine removing the upgrade controller reference. Its the payment processor for the cloud based service, It isnt referenced by any of the core of the project, it just takes payments and upgrades accounts.

**Comment by PhilRumens** [comment]
Great, we won't be doing this locally so removing it should be fine.
